apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vshk-certification.fullname" . }}
  labels: 
    {{- include "vshk-certification.labels" . | nindent 4 }}
data:
  db_host: "{{ .Values.db.host }}"
  db_port: "{{ .Values.db.port }}"
  db_name: "{{ .Values.db.name }}"
