{{- if .Values.pv.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vshk-certification.fullname" . }}-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "{{ include "vshk-certification.fullname" . }}-pv"
  storageClassName: ""
{{- end }}