apiVersion: v1
kind: Secret
type: "Opaque"
metadata:
  name: {{ include "vshk-certification.fullname" . }}
  labels: 
    {{- include "vshk-certification.labels" . | nindent 4 }}
stringData:
  db_user: "{{ .Values.db.user }}"
  db_password: "{{ .Values.db.password }}"